---
- Organizational:
  - action items
  - big visible chart
  - facilitator writes
  - participants write
  - retrospective
  - secretary
  - three things
  - visible agenda

- Ground Rules:
  - no stories
  - one conversation
  - use gestures

- Discussion:
  - break into groups
  - define your role
  - direct group authority
  - fishbowl
  - ground rules
  - ice breaker
  - invite others to talk
  - parking lot
  - talking stick
  - use cards
  
- Language:
  - ask questions with answers
  - I language
  - I see I feel I imagine
  - on a scale of
  - the purpose of the meeting is
  - use declarative language
  - we language
  - what are you going to do about that

- Cards:
  - business process modeling
  - mind map
  - moving parts architecture
  - stack
  
- Time Keeping:
  - ask to extend
  - time box
  - time keeper
  - time stickies
  
- Understanding:
  - one thing
  - rephrase
  - say little
  
- State of Mind:
  - I trust you
  - no attachments
  - no personal agenda
  - people hear what they need to
  - put your distractions on the shelf
  
- Safety:
  - lower my status
  - make mistakes
  - play a game
  - present a problem
  - temperature
